version: "3"
services:
  sentinel: &sentinel
    build: sentinel
    image: sentinel
    env_file: sentinel/.env
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  sentinel1:
    <<: *sentinel
    container_name: sentinel1

  sentinel2:
    <<: *sentinel
    container_name: sentinel2

  sentinel3:
    <<: *sentinel
    container_name: sentinel3

  redis-master:
    container_name: redis-master
    image: redis:5.0.4-alpine

  redis-slave1:
    container_name: redis-slave1
    image: redis:5.0.4-alpine
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  redis-slave2:
    container_name: redis-slave2
    image: redis:5.0.4-alpine
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tapp
    volumes:
      - .:/app
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - sentinel1
      - sentinel2
      - sentinel3
    command: /run_tests

